logging:
  level:
    ROOT: INFO
    com.hust.webchat: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/smart_house?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: hust
    password: 1qazXSW@
    hikari:
      auto-commit: false
      maximum-pool-size: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        generate_statistics: true
        ddl-auto: update
  sql:
    init:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: amc.building.mb@gmail.com
    password: 123456aA@
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    cache-duration: 60 # 1 second, see the ISO 8601 standard
    basename: i18n/messages
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081

security:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: NThlODQ0NTBjYjNlZjEyMGMzYzU4YjM1MTJmNWVkZGIzMzRmZjMxMTUwM2VhZDA2NDA2YTZhMTI4OTQxNmM3N2MzODE5MDQwYzc0YTBiMDU1ZTU5ODdkODgyYTllNTdkZDJkMDg3NWYxYTFhNmRmNGE5YjkzMTczYTQwMGJlNDc=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

application:
  domain: http://localhost:8081

rabbitmq:
  queue-hust-iot-action: queue.hust.iot.action
  queue-hust-iot-stream: queue.hust.iot.stream
  queue-hust-iot-house-sensor: queue.hust.iot.house-sensor
  house-sensor-routing-key: queue.hust.iot.house-sensor-key
  house-sensor-exchange: house-sensor
